spring.application.name=CampusLife
spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/campus_life_simulator_db
#spring.datasource.username=librarymanager
#spring.datasource.password=chiquoc123
spring.datasource.username=root
spring.datasource.password=123456
app.admin.username=admin
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=companyweb14@gmail.com
spring.mail.password=eige noog hnux lgdf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud_name=dxwmeji7c
cloudinary.api_key=663656893185499
cloudinary.api_secret=DDWzW1SsPnU1NPaR-HSqbzScWsg